### ISSUE TITLE
Error Artwork Beef : No result

### ISSUE THREAD

**Issue by cocimho** [rmrector/script.artwork.beef#44]
Hi There !
Sorry for my bad english i'll do my best ^^

I've got a problem with Artwork Beef. since yesterday, i can't put anything on my thumbail's TV show and i don't know why... I can't either take local files...
But with movie, there's no problem its works correctly...
So i try to delete and reinstall it but it's the same...
I have the pictures in the good folder of my TV show, but nothing....

Can u help me please ? thank u very much.
Coci.

"__ERROR: EX_CEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'graphical'
                                            Traceback (most recent call last):
                                              File "C:\Users\salon\AppData\Roaming\Kodi\addons\script.artwork.beef\context_gui.py", line 4, in <module>
                                                main('gui')
                                              File "C:\Users\salon\AppData\Roaming\Kodi\addons\script.artwork.beef\context.py", line 16, in main
                                                processor.process_item(mediatype, dbid, mode)
                                              File "C:\Users\salon\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 147, in process_item
                                                self._manual_item_process(mediaitem, busy)
                                              File "C:\Users\salon\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 171, in _manual_item_process
                                                self._process_item(mediaitem, True, False)
File "C:\Users\salon\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 310, in _process_item
                                                services_hit, error = self.gatherer.getartwork(mediaitem, onlyfs, auto)
                                              File "C:\Users\salon\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\gatherer.py", line 34, in getartwork
                                                mediaitem.uniqueids)
                                              File "C:\Users\salon\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\gatherer.py", line 102, in get_external_artwork
                                                if int(season) not in seasons:
                                            ValueError: invalid literal for int() with base 10: 'graphical'
                                            -->End of Python script error report<--_"

**Comment by charlie2alpha** [comment]
Getting the same error, suspecting recent changes on the  TVDB site again.

**Comment by idorose** [comment]
I'm getting this since yesterday:
`2019-11-15 19:51:59.101 T:13108   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Britannia/extrafanart/
2019-11-15 19:51:59.203 T:1604  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (60.0.14)
2019-11-15 19:52:00.152 T:13064   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Jessica Jones/extrafanart/
2019-11-15 19:52:00.412 T:13064   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Silicon Valley/extrafanart/
2019-11-15 19:52:01.740 T:6792   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/Israeli TV Shows/When Heroes Fly/extrafanart/
2019-11-15 19:52:03.318 T:13064   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/Israeli TV Shows/Shnot Hashmonim/extrafanart/
2019-11-15 19:52:04.357 T:13064   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Victoria/extrafanart/
2019-11-15 19:52:04.607 T:6792   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/The Spy/extrafanart/
2019-11-15 19:52:05.068 T:13108   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Mr Robot/extrafanart/
2019-11-15 19:52:07.683 T:6792   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/13 Reasons Why/extrafanart/
2019-11-15 19:52:09.227 T:5672   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/Israeli TV Shows/Shnot Hashmonim/extrafanart/
2019-11-15 19:52:10.080 T:6792   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/13 Reasons Why/extrafanart/
2019-11-15 19:52:11.799 T:13064   ERROR: Previous line repeats 1 times.
2019-11-15 19:52:11.799 T:13064   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Big Little Lies/extrafanart/
2019-11-15 19:52:12.137 T:6792   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Billions/extrafanart/
2019-11-15 19:52:12.371 T:13108   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Black Mirror/extrafanart/
2019-11-15 19:52:13.109 T:6792   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Britannia/extrafanart/
2019-11-15 19:52:21.316 T:6132   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'graphical'
                                            Traceback (most recent call last):
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\context_gui.py", line 4, in <module>
                                                main('gui')
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\context.py", line 16, in main
                                                processor.process_item(mediatype, dbid, mode)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 147, in process_item
                                                self._manual_item_process(mediaitem, busy)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 171, in _manual_item_process
                                                self._process_item(mediaitem, True, False)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 310, in _process_item
                                                services_hit, error = self.gatherer.getartwork(mediaitem, onlyfs, auto)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\gatherer.py", line 34, in getartwork
                                                mediaitem.uniqueids)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\gatherer.py", line 102, in get_external_artwork
                                                if int(season) not in seasons:
                                            ValueError: invalid literal for int() with base 10: 'graphical'
                                            -->End of Python script error report<--
2019-11-15 19:52:37.364 T:5892   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'graphical'
                                            Traceback (most recent call last):
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\default.py", line 313, in <module>
                                                main()
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\default.py", line 65, in main
                                                processor.process_item(command['mediatype'], int(command['dbid']), command.get('mode', 'auto'))
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 147, in process_item
                                                self._manual_item_process(mediaitem, busy)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 171, in _manual_item_process
                                                self._process_item(mediaitem, True, False)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\artworkprocessor.py", line 310, in _process_item
                                                services_hit, error = self.gatherer.getartwork(mediaitem, onlyfs, auto)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\gatherer.py", line 34, in getartwork
                                                mediaitem.uniqueids)
                                              File "C:\Users\TV-PC\AppData\Roaming\Kodi\addons\script.artwork.beef\lib\gatherer.py", line 102, in get_external_artwork
                                                if int(season) not in seasons:
                                            ValueError: invalid literal for int() with base 10: 'graphical'
                                            -->End of Python script error report<--
2019-11-15 19:52:42.002 T:13064   ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://ROSENTHALNAS/Multimedia/Videos/TV Shows/Jessica Jones/extrafanart/
`

**Comment by rmrector** [comment]
TheTVDB API stopped providing the season number for season artwork, and the field `subKey` that used to hold the season number now contains the string "graphical".

I can improve Artwork Beef's to not throw an error in this case, but season artwork is tough to use without the season number.

**Comment by charlie2alpha** [comment]
Seems they're doing stuff again on the tmdb backend, this should be temporary: https://forums.thetvdb.com/viewtopic.php?f=3&t=60048

**Comment by rmrector** [comment]
Handling of this case improved in 0.27.1.
